name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: docker-compose
        run: | 
          sudo docker-compose up -d --build
          sleep 50


      - name: Run API Tests
        timeout-minutes: 30
        run: |
            chmod +x ./scripts/test-script.sh
            sudo ./scripts/test-script.sh
        env:
          VARIANT: v1
          SERVICE_NAME: bonus-service
          PORT_NUMBER: 8080
      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 2
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v